
import { Button } from "@/components/ui/button";
import { ArrowLeft } from "lucide-react";
import Link from "next/link";

export default function TermsOfServicePage() {
  return (
    <div className="container mx-auto max-w-3xl p-4 sm:p-6 lg:p-8">
        <div className="mb-8">
             <Link href="/dashboard" passHref>
                <Button variant="outline">
                    <ArrowLeft className="mr-2 h-4 w-4"/>
                    Back to App
                </Button>
            </Link>
        </div>
      <div className="prose dark:prose-invert max-w-none">
        <h1 className="text-3xl font-headline font-bold">Terms of Service for MindBud</h1>
        <p className="text-sm text-muted-foreground">Last Updated: {new Date().toLocaleDateString()}</p>
        <p>
            Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the MindBud mobile application (the "Service") operated by MindBud ("us", "we", or "our").
        </p>
        <p>
            Your access to and use of the Service is conditioned upon your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who wish to access or use the Service. By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you do not have permission to access the Service.
        </p>

        <h2 className="font-headline">1. Definitions</h2>
        <ul>
            <li><strong>"Service"</strong> refers to the MindBud application, including all its features, content, and the Bud AI companion.</li>
            <li><strong>"Bud AI"</strong> refers to the generative artificial intelligence companion integrated within the Service, designed to provide conversational support.</li>
            <li><strong>"User"</strong>, <strong>"You"</strong>, and <strong>"Your"</strong> refer to the individual accessing or using the Service.</li>
            <li><strong>"Content"</strong> means any information, text, graphics, or other materials generated, provided, or otherwise made available through the Service, including content generated by Bud AI and content submitted by you.</li>
            <li><strong>"User-Generated Content"</strong> refers to any Content that you create, log, or submit to the Service, including but not limited to mood entries, trigger notes, journal entries, and chat messages.</li>
        </ul>

        <h2 className="font-headline">2. Service Description and Important Disclaimers</h2>
        <h3 className="font-headline text-lg">2.1. Nature of the Service</h3>
        <p>
            MindBud is a mental wellness tool designed to provide support through features such as AI-powered conversational support (Bud AI), mood tracking, activity logging, and a peer-to-peer support chat. The goal of the Service is to help you better understand and manage your emotional well-being.
        </p>
        <h3 className="font-headline text-lg">2.2. NOT a Medical Service</h3>
        <p>
            <strong>CRITICAL: MindBud is not a licensed medical or healthcare provider, and the Service is not a substitute for professional medical advice, diagnosis, or treatment.</strong> The Service, including all interactions with Bud AI, is not intended to be a replacement for clinical therapy, psychiatric care, or any other form of professional healthcare. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition. Never disregard professional medical advice or delay in seeking it because of something you have read or experienced on the Service.
        </p>
        <h3 className="font-headline text-lg">2.3. Emergency and Crisis Situations</h3>
        <p>
            <strong>DO NOT USE THE SERVICE FOR EMERGENCIES.</strong> If you are experiencing a medical emergency, a mental health crisis, or are thinking about suicide or self-harm, please call 911 or the 988 Suicide & Crisis Lifeline immediately. Bud AI is programmed to provide a crisis resource message if it detects a potential crisis, but this feature is not infallible and should not be relied upon as a primary safety mechanism.
        </p>
        <h3 className="font-headline text-lg">2.4. AI-Generated Content Disclaimer</h3>
        <p>
            The Bud AI is an experimental generative artificial intelligence. While we have designed it to be helpful and empathetic, it may produce information that is inaccurate, incomplete, or inappropriate. You acknowledge that any reliance on Content generated by Bud AI is at your own risk. We do not guarantee the accuracy, completeness, or usefulness of any information on the Service and neither adopt nor endorse, nor are we responsible for, the accuracy or reliability of any opinion, advice, or statement made by Bud AI.
        </p>

        <h2 className="font-headline">3. Privacy and Data Usage</h2>
        <p>
            Your privacy is critically important to us. Our data handling practices are designed with your privacy and benefit at the forefront.
        </p>
        <h3 className="font-headline text-lg">3.1. Information We Collect</h3>
        <ul>
            <li><strong>Account Information:</strong> When you create an account, we collect your name and email address to manage your account.</li>
            <li><strong>User-Generated Content:</strong> We collect and store the data you provide to the Service, such as your mood entries, selected triggers, journal entries, activity logs, and chat messages in the anonymous peer support group.</li>
            <li><strong>Interaction Data:</strong> Conversations with Bud AI are processed to provide responses and improve the Service. We may retain this data to maintain conversation history and for model training and safety purposes.</li>
            <li><strong>Technical Data:</strong> We may collect anonymous data about your device and usage of the Service to identify bugs and improve performance.</li>
        </ul>
        <h3 className="font-headline text-lg">3.2. How We Use Your Data</h3>
        <ul>
            <li><strong>To Provide and Personalize the Service:</strong> Your data, such as mood logs and activity surveys, is used to power features like the "Insights" page, helping you identify correlations between your activities and your mood. Conversation history with Bud AI is used to provide context for ongoing discussions.</li>
            <li><strong>To Improve the Service:</strong> We analyze user interaction data in an aggregated and anonymized form to understand how our Service is used, which helps us improve features, fix bugs, and enhance the user experience. Anonymized conversation data may be used to improve the safety, accuracy, and helpfulness of Bud AI.</li>
            <li><strong>To Ensure Safety and Security:</strong> We may use automated systems to monitor User-Generated Content (like chat messages) for violations of our User Conduct policies to maintain a safe environment for all users.</li>
        </ul>
        <h3 className="font-headline text-lg">3.3. Our Data Commitment</h3>
        <p>
            <strong>We will not sell, rent, or lease your personally identifiable information to third parties for marketing purposes.</strong> Your data is used to provide the Service to you. When data is used for analytics or AI model improvement, we take steps to anonymize and aggregate it to protect your privacy.
        </p>

        <h2 className="font-headline">4. User Accounts and Responsibilities</h2>
        <h3 className="font-headline text-lg">4.1. Eligibility</h3>
        <p>You must be at least 18 years of age to create an account and use the Service. By creating an account, you represent and warrant that you meet this age requirement.</p>
        <h3 className="font-headline text-lg">4.2. Account Security</h3>
        <p>You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password. We encourage you to use a "strong" password (a password that uses a combination of upper and lower case letters, numbers, and symbols) with your account. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</p>

        <h2 className="font-headline">5. User-Generated Content and Conduct</h2>
        <h3 className="font-headline text-lg">5.1. Ownership and License</h3>
        <p>You retain ownership of any intellectual property rights that you hold in your User-Generated Content. When you upload or otherwise submit content to our Service, you give us a worldwide license to use, host, store, reproduce, modify, and create derivative works (such as those resulting from translations, adaptations, or other changes we make so that your content works better with our Services). The rights you grant in this license are for the limited purpose of operating, promoting, and improving our Services, and to develop new ones.</p>
        <h3 className="font-headline text-lg">5.2. Prohibited Conduct</h3>
        <p>You agree not to use the Service to:</p>
        <ul>
            <li>Post or transmit any content that is unlawful, harmful, threatening, abusive, harassing, defamatory, vulgar, obscene, or otherwise objectionable.</li>
            <li>Engage in hate speech, discrimination, or threats of violence.</li>
            <li>Share personal identifying information (PII) of yourself or others in public areas of the Service, such as the anonymous group chat.</li>
            <li>Impersonate any person or entity or falsely state or otherwise misrepresent your affiliation with a person or entity.</li>
            <li>Violate any applicable local, state, national, or international law.</li>
            <li>Attempt to interfere with, compromise the system integrity or security of, or decipher any transmissions to or from the servers running the Service.</li>
        </ul>
        <p>We reserve the right to remove any content and/or terminate user accounts for violating these rules.</p>
        
        <h2 className="font-headline">6. Intellectual Property</h2>
        <p>
            The Service and its original content (excluding User-Generated Content), features, and functionality are and will remain the exclusive property of MindBud and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of MindBud.
        </p>

        <h2 className="font-headline">7. Termination</h2>
        <p>
            We may terminate or suspend your account and bar access to the Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever and without limitation, including but not limited to a breach of the Terms. All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.
        </p>
        
        <h2 className="font-headline">8. Indemnification</h2>
        <p>
            You agree to defend, indemnify, and hold harmless MindBud and its licensee and licensors, and their employees, contractors, agents, officers, and directors, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees), resulting from or arising out of a) your use and access of the Service, by you or any person using your account and password, or b) a breach of these Terms.
        </p>

        <h2 className="font-headline">9. Limitation Of Liability</h2>
        <p>
            In no event shall MindBud, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service, including from Bud AI; and (iv) unauthorized access, use, or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence), or any other legal theory, whether or not we have been informed of the possibility of such damage, and even if a remedy set forth herein is found to have failed of its essential purpose.
        </p>
        
        <h2 className="font-headline">10. Disclaimer of Warranties</h2>
        <p>
            Your use of the Service is at your sole risk. The Service is provided on an "AS IS" and "AS AVAILABLE" basis. The Service is provided without warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, non-infringement, or course of performance.
        </p>
        <p>
            MindBud, its subsidiaries, affiliates, and its licensors do not warrant that a) the Service will function uninterrupted, secure, or available at any particular time or location; b) any errors or defects will be corrected; c) the Service is free of viruses or other harmful components; or d) the results of using the Service will meet your requirements.
        </p>

        <h2 className="font-headline">11. Governing Law</h2>
        <p>
            These Terms shall be governed and construed in accordance with the laws of the State of [Your State/Country], United States, without regard to its conflict of law provisions. Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.
        </p>
        
        <h2 className="font-headline">12. Changes to Terms</h2>
        <p>
            We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion. By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms.
        </p>
        
        <h2 className="font-headline">13. Contact Us</h2>
        <p>
            If you have any questions about these Terms, please contact us at: [Your Contact Email/Form Link]
        </p>
      </div>
    </div>
  );
}
